"""initial_schema

Revision ID: 81b3db5280c7
Revises: 
Create Date: 2026-10-07 19:33:21.911051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '81b3db5280c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='filestatus', native_enum=False), nullable=False),
    sa.Column('crs', sa.String(length=100), nullable=True),
    sa.Column('crs_assumed', sa.Boolean(), nullable=False),
    sa.Column('feature_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploaded_files_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_status'), ['status'], unique=False)

    op.create_table('features',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('feature_index', sa.Integer(), nullable=False),
    sa.Column('geometry_type', sa.String(length=50), nullable=False),
    sa.Column('geometry', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('source_crs', sa.String(length=100), nullable=False),
    sa.Column('properties', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=False),
    sa.Column('measurement_status', sa.Enum('OK', 'UNSUPPORTED', 'EMPTY', 'INVALID', 'ERROR', name='measurementstatus', native_enum=False), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('perimeter_m', sa.Float(), nullable=True),
    sa.Column('measurement_crs', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('warnings', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_features_file_id'), ['file_id'], unique=False)
        batch_op.create_index('ix_features_file_id_feature_index', ['file_id', 'feature_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_features_measurement_status'), ['measurement_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_features_measurement_status'))
        batch_op.drop_index('ix_features_file_id_feature_index')
        batch_op.drop_index(batch_op.f('ix_features_file_id'))

    op.drop_table('features')
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_files_status'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_sha256'))

    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
